apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: school-domnak
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: school-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: school-domnak-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: school-domnak
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
