apiVersion: v1
kind: Service
metadata:
  name: school-nginx
  namespace: schooldomnak
spec:
  type: LoadBalancer
  selector:
    app: school-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
