apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-redis
  namespace: schooldomnak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-redis
  template:
    metadata:
      labels:
        app: school-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 10
